### ISSUE TITLE
Totally unusable in the Webpack skeleton

### ISSUE THREAD

**Issue by istrau2** [froala/aurelia-froala-editor#15]
I tried to load this in my aurelia-webpack project and it failed. A couple of issues I noticed at a glance:

1) pacakge.json main should point to an entry file (i.e. dist/index)
2) You can't use System.register explicitly like that (since the webpack skeleton does not use system.js)

**Comment by florinpopescu** [comment]
@istrau2 Thanks for the feedback.

1) package.json do point to index.js located into dist folder:
```
"directories": {
    "lib": "dist",
    "src": "src"
  },
```
2) I modified the compiler (from system.js to common.js).

Can you check if it works now?

**Comment by istrau3** [comment]
@florinpopescu I will check as soon as I can. Thanks for the quick feedback.

**Comment by apawsey** [comment]
Hey.

I've now also tried to include in my webpack based project... I just end up with:
```
WARNING in ./src ^\.\/.*$
Module not found: Error: Can't resolve 'aurelia-froala-editor' in 'C:\my-project-source-tree\src'
 @ ./src ^\.\/.*$
 @ ./~/aurelia-loader-webpack/dist/commonjs/aurelia-loader-webpack.js
 @ multi aurelia
```

I'm still investigating so this isn't just a dump error and run type post, just wanted to raise it in case anyone has the quick answer... otherwise I'll return with more info once I've dug into it a bit more.

Thanks.

**Comment by apawsey** [comment]
With error details in webpack switched on, it shows where it is searching for the package files...
```
[C:\my-project-source-tree\src\node_modules]
[C:\my-project-source-tree\src\aurelia-froala-editor]
[C:\my-project-source-tree\src\aurelia-froala-editor]
[C:\my-project-source-tree\src\aurelia-froala-editor]
[C:\my-project-source-tree\src\aurelia-froala-editor.js]
[C:\my-project-source-tree\src\aurelia-froala-editor.ts]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor.js]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor.ts]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.js]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.js]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.js]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.js]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.js.js]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.js.ts]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index]
[C:\my-project-source-tree\node_modules\aurelia-froala-editor\index.ts]
```

**Comment by apawsey** [comment]
Ok so now I actually got to running the site, and I get another error:
```
bluebird.js:1546 Unhandled rejection TypeError: froala.default is not a function
    at Object.configure (https://localhost:44333/app.bundle.js:54637:16)
    at https://localhost:44333/aurelia.bundle.js:47427:34
From previous event:
    at _loadPlugin (https://localhost:44333/aurelia.bundle.js:47425:40)
    at https://localhost:44333/aurelia.bundle.js:47418:14
From previous event:
    at loadPlugin (https://localhost:44333/aurelia.bundle.js:47417:73)
    at next (https://localhost:44333/aurelia.bundle.js:47678:18)
From previous event:
    at next (https://localhost:44333/aurelia.bundle.js:47678:54)
    at https://localhost:44333/aurelia.bundle.js:47685:14
From previous event:
    at FrameworkConfiguration.apply (https://localhost:44333/aurelia.bundle.js:47670:42)
    at Aurelia.start (https://localhost:44333/aurelia.bundle.js:47287:21)
    at Object._callee$ (https://localhost:44333/app.bundle.js:24316:33)
    at tryCatch (https://localhost:44333/aurelia-bootstrap.bundle.js:6382:40)
    at Generator.invoke [as _invoke] (https://localhost:44333/aurelia-bootstrap.bundle.js:6656:22)
    at Generator.prototype.(anonymous function) [as next] (https://localhost:44333/aurelia-bootstrap.bundle.js:6415:21)
    at https://localhost:44333/app.bundle.js:24279:65
From previous event:
    at __awaiter (https://localhost:44333/app.bundle.js:24259:12)
    at Object.configure (https://localhost:44333/app.bundle.js:24285:12)
    at https://localhost:44333/aurelia-bootstrap.bundle.js:7556:27
From previous event:
    at config (https://localhost:44333/aurelia-bootstrap.bundle.js:7555:46)
    at handleApp (https://localhost:44333/aurelia-bootstrap.bundle.js:7546:10)
    at https://localhost:44333/aurelia-bootstrap.bundle.js:7574:9
From previous event:
    at https://localhost:44333/aurelia-bootstrap.bundle.js:7571:44
From previous event:
    at run (https://localhost:44333/aurelia-bootstrap.bundle.js:7568:24)
    at Object.<anonymous> (https://localhost:44333/aurelia-bootstrap.bundle.js:7593:1)
    at Object.aurelia-bootstrapper-webpack (https://localhost:44333/aurelia-bootstrap.bundle.js:7594:30)
    at __webpack_require__ (https://localhost:44333/aurelia-bootstrap.bundle.js:57:38)
    at Object.414 (https://localhost:44333/aurelia-bootstrap.bundle.js:6997:1)
    at __webpack_require__ (https://localhost:44333/aurelia-bootstrap.bundle.js:57:38)
    at 16 (https://localhost:44333/aurelia-bootstrap.bundle.js:140:18)
    at https://localhost:44333/aurelia-bootstrap.bundle.js:143:10
```
Still looking into this...

**Comment by florinpopescu** [comment]
Hi @apawsey 

The function `default` comes from the import: `import * as froala from "froala-editor/./js/froala_editors.min";` , so it not a Froala Editor function. `default` is used for loading froala_editor.min.js file and somehow I think your import does not work. Can you check your import please?

Also, can you please provide your webpack configuration to better replicate the problem?

Thanks,
Florin

**Comment by florinpopescu** [comment]
@apawsey Also, have you tried to use aurelia-webpack-plugin for "Module not found: Error: Can't resolve 'aurelia-froala-editor' in ..." error?

**Comment by apawsey** [comment]
@florinpopescu I'm not sure what you mean by use the aurelia-webpack-plugin?  My site is based on the aurelia typescript webpack skeleton project, so the plugin is already being used.  I'm not sure if perhaps you think there is another configuration option I should use?  As I said, my understanding of package.json files, without a main attribute, the module has no entry point.  Adding it immediately makes it work.

**Comment by apawsey** [comment]
@florinpopescu it will be difficult to give my webpack configuration as it's based on easy-webpack, and therefore is composed of a lot of functions...

I understand the function default is added by the `import * as`... call, but it appears nothing is being returned from the require function that is directly above it.

**Comment by stefanneculai** [comment]
@apawsey The current master version makes it webpack compatible.
