### ISSUE TITLE
__moduleName is not defined

### ISSUE THREAD

**Issue by dabide** [froala/aurelia-froala-editor#25]
Using the editor without config works fine. However, when froala-editor plugins are activated, I get the following error:

```
Unhandled rejection ReferenceError: __moduleName is not defined
    at Object.addPlugin (http://localhost:9000/jspm_packages/npm/aurelia-froala-editor@2.3.4-9/index.js:33:83)
    at eval (http://localhost:9000/dist/main.js:8:14)
    at r.configure (http://localhost:9000/jspm_packages/npm/aurelia-froala-editor@2.3.4-9/index.js:50:2)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-framework@1.0.2/aurelia-framework.js:281:36)
    at r (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:33:7722)
    at i._settlePromiseFromHandler (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13044)
    at i._settlePromise (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:13847)
    at i._settlePromise0 (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:14548)
    at i._settlePromises (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:32:15878)
    at r._drainQueue (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3148)
    at r._drainQueues (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:3209)
    at drainQueues (http://localhost:9000/jspm_packages/npm/bluebird@3.4.1/js/browser/bluebird.min.js:31:1238)
```

main.js:
```
    .plugin('aurelia-froala-editor', config => {
      config.addPlugin("draggable");
    });
```

**Comment by dabide** [comment]
Replacing `__moduleName` with `module.id` in index.js fixes it.

**Comment by dabide** [comment]
Have you had a look at this, and the attached pull request?

**Comment by henning-krause** [comment]
Hi,

my PR also covers this (https://github.com/froala/aurelia-froala-editor/pull/28) among other things but hasn't been accepted yet because it does not fix all WebPack related issues. The Froala team is working on it, AFAIK.

**Comment by stefanneculai** [comment]
This is no longer used on the current master because it is incompatible with webpack. Therefore, closing this.
